version = 1

[[annotations]]
path = [
  "extension/.vscodeignore",
  "**/package.json",
  "**/tsconfig.json",
  "**/tsconfig.app.json",
  "**/tsconfig.bun.json",
  "**/.gitignore",
  "**/.editorconfig",
  ".vscode/extensions.json",
]
SPDX-FileCopyrightText = "2025 Velociraptor115"
SPDX-License-Identifier = "Apache-2.0"


[[annotations]]
path = [
  "**/*.md",
]
SPDX-FileCopyrightText = "2025 Velociraptor115"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
  "**/bun.lock",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
